name: HW1_CI
on: [push]
jobs:
  GTest_and_cov:
    name: GTest and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Build Tests
        uses: actions/checkout@v2
      - run: cmake -B build -DCOVERAGE=ON
      - run: make -C build
      
      - name: Run tests
        run: ./build/lib/functions/tests/test_functions
      - run: ./build/lib/restoraunt/tests/test_restoraunt
      
      - name: Generate coverage report
        run: cd ./build
      #- run: lcov -t "TESTS" -d ./build/lib -c -o ./build/covrep.info
      - run: gcovr -r . -x -o ./build/gcovrrep.xml
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./build/gcovrrep.xml
