name: HW1_CI
on: [push]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    cmake_extra_args: ""
    steps:
      - uses: actions/checkout@v2
      - run: cmake -B build
      - run: make -C build